# ansible-inventory -i inventory.yaml --list
vms:
  hosts:
    vm01:
      ansible_host: 44.218.126.15
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: "/Users/kunalverma/.ssh/komiser-aws"
      
